version: '3'
services:
  app:
    build:
      context: .
      dockerfile: 'development-Dockerfile'
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/portfolio
      - public-data:/portfolio/public
      - tmp-data:/portfolio/tmp
      - log-data:/portfolio/log
    depends_on:
      - db
      - test-db
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'keisuke'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: good_development
    volumes:
      # - ./mysql-confd:/etc/mysql/conf.d
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'
  test-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'keisuke'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: good_test
    ports:
      - '3307:3306'
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/portfolio/public
      - tmp-data:/portfolio/tmp
    tty: true
    stdin_open: true
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

# docker-compose -f development-docker-compose.yml build
# docker-compose -f development-docker-compose.yml up -d
# docker-compose -f development-docker-compose.yml down
# docker-compose -f development-docker-compose.yml run app rails db:create db:migrate
# docker-compose -f development-docker-compose.yml run app bin/rspec