version: '3'
services:
  app:
    build:
      context: .
      dockerfile: 'production-Dockerfile'
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/portfolio
      - public-data:/portfolio/public
      - tmp-data:/portfolio/tmp
      - log-data:/portfolio/log
    environment:
      RAILS_ENV: production
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/portfolio/public
      - tmp-data:/portfolio/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

# docker-compose -f production-docker-compose.yml build
# docker-compose -f production-docker-compose.yml up -d
# docker-compose -f production-docker-compose.yml down