version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting db
          command: sleep 25
      - run:
          name: set up db
          command: docker-compose run app rails db:create db:migrate
      - run:
          name: do test
          command: docker-compose bin/rspec
      - run:
          name: docker-compose down
          command: docker-compose down